export const CREATE_FACEBOOK_USER_FULFILLED = 'CREATE_FACEBOOK_USER_FULFILLED';
export const CREATE_FACEBOOK_USER_REJECTED = 'CREATE_FACEBOOK_USER_REJECTED';
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const GET_USER_REJECTED = "GET_USER_REJECTED";
