export const CREATE_FACEBOOK_USER_FULFILLED = 'CREATE_FACEBOOK_USER_FULFILLED';
export const CREATE_FACEBOOK_USER_REJECTED = 'CREATE_FACEBOOK_USER_REJECTED';
export const CREATE_VK_USER_FULFILLED = 'CREATE_VK_USER_FULFILLED';
export const CREATE_VK_USER_REJECTED = 'CREATE_VK_USER_REJECTED';
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const GET_USER_REJECTED = "GET_USER_REJECTED";
export const USER_LOGIN = "LOGIN";
export const USER_LOGOUT = "LOGOUT";

export const GET_SAVED_POSTS_FULFILLED = "GET_SAVED_POSTS_FULFILLED";
export const GET_SAVED_POSTS_REJECTED = "GET_SAVED_POSTS_REJECTED";

export const SAVE_POST_TO_DASHBOARD_FULFILLED = "SAVE_POST_TO_DASHBOARD_FULFILLED";
export const SAVE_POST_TO_DASHBOARD_REJECTED = "SAVE_POST_TO_DASHBOARD_REJECTED";

export const DELETE_POST_FROM_DASHBOARD_FULFILLED = "DELETE_POST_FROM_DASHBOARD_FULFILLED";
export const DELETE_POST_FROM_DASHBOARD_REJECTED = "DELETE_POST_FROM_DASHBOARD_REJECTED";


export const GET_IS_POST_EXIST_FULFILLED = "GET_IS_POST_EXIST_FULFILLED";
export const GET_IS_POST_EXIST_REJECTED = "GET_IS_POST_EXIST_REJECTED";
