export const FETCH_SINGLE_POST_FULFILLED = 'FETCH_SINGLE_POST_FULFILLED';
export const FETCH_SINGLE_POST_REJECTED = 'FETCH_SINGLE_POST_REJECTED';

export const FETCH_NATIVE_POSTS_FULFILLED = 'FETCH_NATIVE_POSTS_FULFILLED';
export const FETCH_NATIVE_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

export const FETCH_ART_POSTS_FULFILLED = 'FETCH_ART_POSTS_FULFILLED';
export const FETCH_ART_POSTS_REJECTED = 'FETCH_ART_POSTS_REJECTED';

export const FETCH_SETS_POSTS_FULFILLED = 'FETCH_SETS_POSTS_FULFILLED';
export const FETCH_SETS_POSTS_REJECTED = 'FETCH_SETS_POSTS_REJECTED';

export const FETCH_TOP_SETS_FULFILLED = 'FETCH_TOP_SETS_FULFILLED';
export const FETCH_TOP_SETS_REJECTED = 'FETCH_TOP_SETS_REJECTED';
export const FETCH_TOP_NATIVE_FULFILLED = 'FETCH_TOP_NATIVE_FULFILLED';
export const FETCH_TOP_NATIVE_REJECTED = 'FETCH_TOP_NATIVE_REJECTED';

export const FETCH_RELATED_POSTS_FULFILLED = 'FETCH_RELATED_POSTS_FULFILLED';
export const FETCH_RELATED_POSTS_REJECTED = 'FETCH_RELATED_POSTS_REJECTED';

export const SEARCH_POST_FULFILLED = 'SEARCH_POST_FULFILLED';
export const SEARCH_POST_REJECTED = 'SEARCH_POST_REJECTED';




